### ISSUE TITLE
Ошибка на 7 задании

### ISSUE THREAD

**Issue by andkarelin** [bem/do-it-yourself-workshop#22]
Добрый день!

Застрял на 7-ом задании. Создал файлы стилей, прописал туда правила, при попытке собрать проект (bem make) выдается следующая ошибка:

<addr>
util.error: Use console.error instead
TypeError: stylus:115:67
   111| {
   112|     border: 0;
   113| }
   114| 
   115| /\* ../../libs/bem-components/common.blocks/image/image.styl end */
--------------------------------------------------------------------------^
   116| 

Cannot read property 'block' of undefined

```
at Group.block (/Users/akarelin/Desktop/tools/do-it-yourself-workshop/bfs-stub/node_modules/stylus/lib/nodes/group.js:48:23)
at Group.clone (/Users/akarelin/Desktop/tools/do-it-yourself-workshop/bfs-stub/node_modules/stylus/lib/nodes/group.js:90:21)
at /Users/akarelin/Desktop/tools/do-it-yourself-workshop/bfs-stub/node_modules/stylus/lib/nodes/block.js:93:21
at Array.forEach (native)
at Block.clone (/Users/akarelin/Desktop/tools/do-it-yourself-workshop/bfs-stub/node_modules/stylus/lib/nodes/block.js:92:14)
at Group.clone (/Users/akarelin/Desktop/tools/do-it-yourself-workshop/bfs-stub/node_modules/stylus/lib/nodes/group.js:90:28)
at /Users/akarelin/Desktop/tools/do-it-yourself-workshop/bfs-stub/node_modules/stylus/lib/nodes/root.js:65:21
at Array.forEach (native)
at Root.clone (/Users/akarelin/Desktop/tools/do-it-yourself-workshop/bfs-stub/node_modules/stylus/lib/nodes/root.js:64:14)
at MemoryCache.set (/Users/akarelin/Desktop/tools/do-it-yourself-workshop/bfs-stub/node_modules/stylus/lib/cache/memory.js:25:21)
```

</addr>

В чем может быть проблема?

**Comment by tavriaforever** [comment]
Похоже на ошибку в синтаксисе stylus

**Comment by andkarelin** [comment]
Я, в общем-то, никакого stylus не писал. Все четко по заданию. Только CSS-файлы.

**Comment by tavriaforever** [comment]
@dab @sipayRT Ребята посмотрите что там

**Comment by sipayRT** [comment]
@andkarelin привет. Попробуй установить зависимости - в папке `bfs-stub` напиши `npm i`. Перед этим удали папку `libs` внутри `bfs-stub`

**Comment by andkarelin** [comment]
Сделал. После этого запустил bem make еще раз. Не помогло.

**Comment by sipayRT** [comment]
@andkarelin я проверил у себя - все ок. Скинь ссылку на свою версию сгенеренного проекта

**Comment by andkarelin** [comment]
Вот: https://github.com/andkarelin/bem-workshop

**Comment by sipayRT** [comment]
ага, разобрался. Все дело в том как ты скопировал стили. Например, у тебя сейчас

```
 .content
    {
        padding: 10px 10%;

        column-count: 4;
        column-gap: 15px;
    }
```

Свиду обычные стили, но на самом деле у тебя перед `.content` стоит пробел с какой-то странной кодировкой. Если ты во всех css-файлах поправишь эти пробелы, то все будет ок. Ты можешь сделать это автоматически в любом IDE.

**Comment by andkarelin** [comment]
Точно! Переписал стили руками и все стало ок. Спасибо большое!
